# generated by bin/generate_component_manifest_files.py


def __getattr__(name):
    _imports = {
        "*": ".declarative_component_schema",
    }
    if name in _imports:
        import importlib
        mod = importlib.import_module(_imports[name], package=__name__)
        return getattr(mod, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
